version: "3.7"
services:
#NODE-RED
   node-red:
    container_name: asn-questgiver
    user: "1000"
    network_mode: host
    restart: unless-stopped
    image: skadakar/asn-questgiver:latest
    ports:
      - "1880:1880"
